### ISSUE TITLE
cannot load such file -- acl9/controller_extensions (LoadError)

### ISSUE THREAD

**Issue by maralik** [be9/acl9#100] opened 2016-02-09 16:15 UTC
Hello!
When I deploy app to AWS Beanstalk I'm getting this error:

> /opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.1.11/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- acl9/controller_extensions (LoadError)

Is it a compatibility issue?

```
source 'https://rubygems.org'

gem 'puma'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.11'
# Use sqlite3 as the database for Active Record
gem 'mysql2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem "paranoia", "~> 2.0"

group :development do
  gem 'better_errors'
  gem "byebug"
  gem "binding_of_caller"
end

# Support of CSV and MS Excel
# @author maralik | David Maralík
# @date 09/08/15 15:04 UTC
gem 'roo', '~> 2.1.0'
gem 'roo-xls'

gem 'render_anywhere', :require => false

gem 'libv8'
gem "therubyracer"
gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
gem "twitter-bootstrap-rails"

gem 'font-awesome-sass', '~> 4.5.0'

gem 'devise'

gem 'acl9', '~> 2.0'

gem 'nokogiri'

gem 'will_paginate', '~> 3.0.6'
gem 'will_paginate-bootstrap'

gem 'i18n_generators'

gem 'jquery-ui-rails'
gem 'rails-jquery-autocomplete'

#gem 'bootstrap-datepicker-rails'
gem 'date_picker'

gem 'jquery-turbolinks'
```

```
GEM
  remote: https://rubygems.org/
  specs:
    acl9 (2.1.1)
      rails (~> 4.0)
    actionmailer (4.1.11)
      actionpack (= 4.1.11)
      actionview (= 4.1.11)
      mail (~> 2.5, >= 2.5.4)
    actionpack (4.1.11)
      actionview (= 4.1.11)
      activesupport (= 4.1.11)
      rack (~> 1.5.2)
      rack-test (~> 0.6.2)
    actionview (4.1.11)
      activesupport (= 4.1.11)
      builder (~> 3.1)
      erubis (~> 2.7.0)
    activemodel (4.1.11)
      activesupport (= 4.1.11)
      builder (~> 3.1)
    activerecord (4.1.11)
      activemodel (= 4.1.11)
      activesupport (= 4.1.11)
      arel (~> 5.0.0)
    activesupport (4.1.11)
      i18n (~> 0.6, >= 0.6.9)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.1)
      tzinfo (~> 1.1)
    arel (5.0.1.20140414130214)
    bcrypt (3.1.10)
    better_errors (0.9.0)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    builder (3.2.2)
    byebug (6.0.2)
    coderay (1.1.0)
    coffee-rails (4.0.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    commonjs (0.2.7)
    date_picker (0.0.8)
      rails (>= 4.0.3)
    debug_inspector (0.0.2)
    devise (3.5.4)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    domain_name (0.5.25)
      unf (>= 0.0.5, < 1.0.0)
    erubis (2.7.0)
    execjs (2.6.0)
    font-awesome-sass (4.5.0)
      sass (>= 3.2)
    hike (1.2.3)
    http-cookie (1.0.2)
      domain_name (~> 0.5)
    i18n (0.7.0)
    i18n_generators (2.0.0)
      mechanize
      rails (>= 3.0.0)
    jbuilder (2.3.1)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (3.1.4)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-turbolinks (2.1.0)
      railties (>= 3.1.0)
      turbolinks
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.3)
    less (2.6.0)
      commonjs (~> 0.2.7)
    less-rails (2.7.0)
      actionpack (>= 4.0)
      less (~> 2.6.0)
      sprockets (> 2, < 4)
      tilt
    libv8 (3.16.14.11)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mechanize (2.7.4)
      domain_name (~> 0.5, >= 0.5.1)
      http-cookie (~> 1.0)
      mime-types (>= 1.17.2, < 3)
      net-http-digest_auth (~> 1.1, >= 1.1.1)
      net-http-persistent (~> 2.5, >= 2.5.2)
      nokogiri (~> 1.6)
      ntlm-http (~> 0.1, >= 0.1.1)
      webrobots (>= 0.0.9, < 0.2)
    mime-types (2.6.2)
    mini_portile (0.6.2)
    minitest (5.8.0)
    multi_json (1.11.2)
    mysql2 (0.3.18)
    net-http-digest_auth (1.4)
    net-http-persistent (2.9.4)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    ntlm-http (0.1.1)
    orm_adapter (0.5.0)
    paranoia (2.1.3)
      activerecord (~> 4.0)
    puma (2.16.0)
    rack (1.5.5)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.1.11)
      actionmailer (= 4.1.11)
      actionpack (= 4.1.11)
      actionview (= 4.1.11)
      activemodel (= 4.1.11)
      activerecord (= 4.1.11)
      activesupport (= 4.1.11)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.1.11)
      sprockets-rails (~> 2.0)
    rails-jquery-autocomplete (1.0.3)
      rails (>= 3.2)
    railties (4.1.11)
      actionpack (= 4.1.11)
      activesupport (= 4.1.11)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    rdoc (4.2.0)
    ref (2.0.0)
    render_anywhere (0.0.12)
      rails (>= 3.0.7)
    responders (1.1.2)
      railties (>= 3.2, < 4.2)
    roo (2.1.1)
      nokogiri (~> 1)
      rubyzip (~> 1.1, < 2.0.0)
    roo-xls (1.0.0)
      nokogiri
      roo (>= 2.0.0beta1, < 3)
      spreadsheet (> 0.9.0)
    ruby-ole (1.2.11.8)
    rubyzip (1.1.7)
    sass (3.2.19)
    sass-rails (4.0.5)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.2.2)
      sprockets (~> 2.8, < 3.0)
      sprockets-rails (~> 2.0)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    spreadsheet (1.0.5)
      ruby-ole (>= 1.0)
    spring (1.4.0)
    sprockets (2.12.4)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    therubyracer (0.12.2)
      libv8 (~> 3.16.14.0)
      ref
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    turbolinks (2.5.3)
      coffee-rails
    twitter-bootstrap-rails (3.2.0)
      actionpack (~> 4.1)
      execjs (~> 2.2)
      rails (~> 4.1)
      railties (~> 4.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.1)
    warden (1.2.4)
      rack (>= 1.0)
    webrobots (0.1.2)
    will_paginate (3.0.7)
    will_paginate-bootstrap (1.0.1)
      will_paginate (>= 3.0.3)

PLATFORMS
  ruby

DEPENDENCIES
  acl9 (~> 2.0)
  better_errors
  binding_of_caller
  byebug
  coffee-rails (~> 4.0.0)
  date_picker
  devise
  font-awesome-sass (~> 4.5.0)
  i18n_generators
  jbuilder (~> 2.0)
  jquery-rails
  jquery-turbolinks
  jquery-ui-rails
  less-rails
  libv8
  mysql2
  nokogiri
  paranoia (~> 2.0)
  puma
  rails (= 4.1.11)
  rails-jquery-autocomplete
  render_anywhere
  roo (~> 2.1.0)
  roo-xls
  sass-rails (~> 4.0.3)
  sdoc (~> 0.4.0)
  spring
  therubyracer
  turbolinks
  twitter-bootstrap-rails
  uglifier (>= 1.3.0)
  will_paginate (~> 3.0.6)
  will_paginate-bootstrap

BUNDLED WITH
   1.10.5

```

**Comment by smathy** [comment] 2016-02-29 16:35
I can't explain that error, requiring other gems is something commonplace that virtually all gems do. Without a stacktrace I can't be certain, but the only place that does a `require "acl9/controller_extensions" is [here](https://github.com/be9/acl9/blob/master/lib/acl9.rb#L3)

This is the exact same thing done [by Arel here](https://github.com/rails/arel/blob/master/lib/arel.rb#L1-L21), [by bcrypt here](https://github.com/codahale/bcrypt-ruby/blob/master/lib/bcrypt.rb#L19-L21) and I could go on through all the other gems that don't seem to be causing a problem for you.

I suspect that my gem is triggering the error because it's the first to be loaded. If you remove it and try again do you get the same error for a different gem then?

Might point to a misconfiguration.

I can't reproduce this in 4.1.11 or in fact any combination of ruby or rails, so I'm closing this issue, if you uncover more information then please feel free to reopen this issue with that information.

**Closed by smathy** 2016-02-29 16:35 UTC

**Comment by maralik** [comment] 2016-03-01 08:25
If I remove acl9 gem everything else works. We already use another gem, no problem.

**Comment by smathy** [comment] 2016-03-01 15:11
:+1: very weird

**Comment by smathy** [comment] 2016-03-07 20:54
Just for anyone else following this, I found the problem (thanks to @maralik and @richcfml for their help/patience) - it was a missing world read permission on some files in the `.gem` itself.

I've released version 2.1.2 with the fix.

**Comment by richcfml** [comment] 2016-03-07 21:14
Thank you for your all of your help and for the efficient response when
problems come up.

---------------------------------------------------------------
Richard Ardila
P: 404.798.3317

**Comment by smathy** [comment] 2016-03-07 22:05
No problem at all, I really appreciate when people take the time to raise an issue.

**Comment by maralik** [comment] 2016-03-08 07:35
Thank you a lot!
